# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    # Run code analysis for all projects/solutions, such that code analysis violations break the build.
    - name: Run dotnet format (code formatting check)
      run: dotnet format --report format.sarif --report-format=sarif --verbosity detailed
      continue-on-error: true
    - name: Upload format report
      uses: actions/upload-artifact@v2
      with:
        name: format-report
        path: format.sarif
    - name: Annotate code with format errors
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: format.sarif
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
