# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    # Run code analysis for all projects/solutions, such that code analysis violations break the build.
    - name: Run dotnet format (code formatting check)
      run: dotnet format --check --verbosity detailed
      continue-on-error: true
    - name: Run static code analysis with Roslyn Analyzers
      run: dotnet build --no-restore -p:TreatWarningsAsErrors=true
      continue-on-error: true
    - name: Run tests and collect code coverage
      run: |
        dotnet test --no-build --collect:"XPlat Code Coverage"
        reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage -reporttypes:Html

    - name: Upload code analysis results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: code-analysis-results
        path: |
          **/*.csproj.FormatAnalysis.txt
          **/MSBuildWarnings.txt
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
